### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by alm0gan** [yastrebksv/TrackNet#2]
in Run python gt_gen.py <args> what does the args mean?
it gives me an error. what do i need to write insread of args?

**Comment by alm0gan** [comment]
doesnt matter, i understood

**Comment by mafiat** [comment]
i have a question with this. I tried to Run python gt_gen.py and i dont get the folder structure that you describe . it doesnt create /gts and /images folders. Am I doing something wrong or there are issues with the py file?
