### ISSUE TITLE
why precision is 0?

### ISSUE THREAD

**Issue by hecowang** [yastrebksv/TrackNet#4]
Hi,  I download the datasets from https://drive.google.com/drive/folders/11r0RUaQHX7I3ANkaYG4jOxXK1OYo01Ut
put dataset to `datasets/TrackNet/images`,  then use gt_gen.py to generate gts and labels.  

however,  after 50 epoch, the precision is still 0.

**Comment by yastrebksv** [comment]
Hello, it is quite normal. Jump in accuracy from zero occurs between 50 and 150 epochs.

**Comment by yastrebksv** [comment]
<img width="259" alt="tracknet_precision" src="https://user-images.githubusercontent.com/16306749/232288000-6e9a88b0-d5f0-43d1-8659-88f7d24c76dc.png">
This is typical log from tensorboard
