### ISSUE TITLE
Offset between ball tracking circle and the target

### ISSUE THREAD

**Issue by 10wei1000** [yastrebksv/TrackNet#5]
Hello,

Thank you so much for the great work porting tracknet to PyTorch. The only problem I found is that the output of tracking always has an offset to the real target in the output video (somehow upper left to the real one). Any idea on how to solve it would be much appreciated!

Best regards,
wei1000

**Comment by yastrebksv** [comment]
Hello!
Frankly speaking, I don't have such problem. I checked predictions in the test set and drew histogram of model errors
<img width="673" alt="xy_diffs" src="https://github.com/yastrebksv/TrackNet/assets/16306749/cb4a555d-cb65-4aa7-849d-fff2a3c53d58">
The median prediction error of x coordinate is 0.65 pixels, the median prediction error of y coordinate is 0.3 pixels

If you have an offset between target and predicted points, you can add this difference to postprocessing.

**Comment by 10wei1000** [comment]
Hello, thank you for your reply! I undertand what is the reason now. The problem is due to the "scale" in postprocessing, if one needs to adjust the network output szie, he or she needs to do this not only according to the magnifications of raw input height, width to 360, 640 respectively, but also the scale in postprocessing, which is 2 by default.
